# Replace

In [35]:
import pandas as pd
csv = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" )
csv

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20   NaN
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20   NaN
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20   NaN
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20   NaN
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20   NaN
16  20:56:28                Komal Koli   2nd year     AI   Oct-20   NaN
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20   NaN
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20   NaN
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20   NaN
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20   NaN
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20   NaN
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20   NaN
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN   NaN
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [22]:
csv.replace(to_replace="Omkar Eknath Vaidya " ,value="kishor")

        Time                       Name      Year Branch    Score  Rank
0   20:53:27                     kishor  3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE   Jul-20   NaN
26  20:43:23               Shreya ukey   2nd year     AI   Jun-20  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE   May-20  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [24]:
csv.replace([x for x in range(1,35)] , 22)

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20  22.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20  22.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20  22.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20  22.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20  22.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20  22.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20  22.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20  22.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20  22.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  22.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  22.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  22.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  22.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  22.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  22.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  22.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  22.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  22.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  22.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  22.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  22.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE   Jul-20   NaN
26  20:43:23               Shreya ukey   2nd year     AI   Jun-20  22.0
27  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20  22.0
28  20:46:03            Sachin Meshram   3rd year    CSE   May-20  22.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20  22.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20  22.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  22.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [27]:
csv.replace({"Name":"[A-Z]"} , 22 , regex= True)

        Time Name      Year Branch    Score  Rank
0   20:53:27   22  3rd year     AI  16 / 20   1.0
1   20:51:13   22  2nd year     AI  15 / 20   2.0
2   21:00:53   22  3rd year     IT  15 / 20   3.0
3   21:00:43   22  3rd year     IT  14 / 20   4.0
4   20:40:01   22  3rd year     AI  13 / 20   5.0
5   20:53:06   22  3rd year    CSE  13 / 20   6.0
6   21:00:00   22  2nd year     IT  13 / 20   7.0
7   21:00:21   22  2nd year    CSE  13 / 20   8.0
8   21:06:03   22  4th year    CSE  13 / 20   9.0
9   20:48:38   22  3rd year    CSE   Dec-20  10.0
10  20:58:20   22  3rd year     IT   Nov-20  11.0
11  20:41:13   22  3rd year    CSE   Oct-20  12.0
12  20:43:26   22  3rd year    CSE   Oct-20   NaN
13  20:46:43   22  4th year    CSE   Oct-20  14.0
14  20:48:23   22  3rd year     AI   Oct-20  15.0
15  20:52:28   22  2nd year     AI   Oct-20  16.0
16  20:56:28   22  2nd year     AI   Oct-20  17.0
17  20:57:19   22  3rd year     AI   Oct-20   NaN
18  21:03:39   22  2nd year    CSE   Sep-20  19.0
19  21:05:36   22  3rd year     AI   Sep-20  20.0
20  20:38:32   22  2nd year    CSE   Aug-20   NaN
21  20:39:09   22  2nd year    CSE   Aug-20  22.0
22  20:41:13   22  3rd year    CSE   Aug-20  23.0
23  20:52:34   22  3rd year    CSE   Aug-20  24.0
24  20:48:03   22  2nd year     AI   Jul-20  25.0
25  20:49:16   22  2nd year    CSE   Jul-20   NaN
26  20:43:23   22  2nd year     AI   Jun-20  27.0
27  20:44:48   22  3rd year    CSE   Jun-20  28.0
28  20:46:03   22  3rd year    CSE   May-20  29.0
29  20:49:24   22  3rd year    CSE   May-20  30.0
30  20:45:36   22  3rd year    CSE   Apr-20  31.0
31       NaN  NaN       NaN    NaN      NaN   NaN
32  21:00:28   22  2nd year    CSE   Apr-20  33.0
33  20:45:22   22  3rd year    CSE   Feb-20   NaN
34  21:03:29   22  3rd year    CSE   0 / 20  35.0

In [29]:
csv.replace("3rd year",method= "ffill")

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   2nd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  2nd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   2nd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  2nd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   4th year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   4th year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  4th year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   4th year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  4th year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  2nd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   2nd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   2nd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  2nd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE   Jul-20   NaN
26  20:43:23               Shreya ukey   2nd year     AI   Jun-20  27.0
27  20:44:48              Nikhil Surkar  2nd year    CSE   Jun-20  28.0
28  20:46:03            Sachin Meshram   2nd year    CSE   May-20  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  2nd year    CSE   May-20  30.0
30  20:45:36    Ritik Fulchand Rajgire   2nd year    CSE   Apr-20  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  2nd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   2nd year    CSE   0 / 20  35.0

In [32]:
csv.replace("2nd year" , method="ffill",limit=2)

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  3rd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   3rd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   3rd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  3rd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   3rd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   3rd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   3rd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   3rd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  3rd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   3rd year    CSE   Jul-20   NaN
26  20:43:23               Shreya ukey   2nd year     AI   Jun-20  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE   May-20  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik       NaN    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [34]:
csv.replace("2nd year" , method="ffill",limit=2 ,inplace=True)
csv

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  3rd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   3rd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   3rd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  3rd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   3rd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   3rd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   3rd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   3rd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  3rd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   3rd year    CSE   Jul-20   NaN
26  20:43:23               Shreya ukey   3rd year     AI   Jun-20  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE   May-20  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik       NaN    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

# interpolate

In [37]:
import pandas as pd 

csv = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" )
csv

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20   NaN
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20   NaN
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20   NaN
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20   NaN
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20   NaN
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20   NaN
16  20:56:28                Komal Koli   2nd year     AI   Oct-20   NaN
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20   NaN
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20   NaN
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20   NaN
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20   NaN
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20   NaN
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20   NaN
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN   NaN
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN   NaN
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20   NaN
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [49]:
csv.interpolate(limit=3) #only work for the number

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20  13.0
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20   NaN
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20   NaN
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20   NaN
16  20:56:28                Komal Koli   2nd year     AI   Oct-20   NaN
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20   NaN
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20   NaN
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20   NaN
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20   NaN
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20   NaN
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20   NaN
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20   NaN
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20   NaN
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN   NaN
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN  32.0
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20  34.0
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [45]:
csv.interpolate(method= "cubic" ,axis =0)

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20  13.0
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20  18.0
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20  21.0
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN  26.0
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN  32.0
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20  34.0
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [52]:
import pandas as pd
csv = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv"  )
csv.interpolate(limit_area ="inside") # inside or

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20  13.0
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20  18.0
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20  21.0
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN  26.0
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN  32.0
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20  34.0
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0

In [54]:
csv.interpolate(inplace=True)

csv

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20  13.0
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20  18.0
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20  21.0
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE      NaN  26.0
26  20:43:23               Shreya ukey   2nd year     AI      NaN  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE      NaN  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE      NaN  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE      NaN  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE      NaN  31.0
31       NaN                        NaN       NaN    NaN      NaN  32.0
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20  34.0
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0