# Read CSV

In [19]:
import pandas as pd
csv_1 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv")

csv_1

    20:53:27       Omkar Eknath Vaidya   3rd year   AI  16 / 20   1
0   20:51:13      Shreya Ravindra Tiple  2nd year   AI  15 / 20   2
1   21:00:53               Sahil Gedam   3rd year   IT  15 / 20   3
2   21:00:43                Akash Bitle  3rd year   IT  14 / 20   4
3   20:40:01           Dewank Bawankar   3rd year   AI  13 / 20   5
4   20:53:06         Bhairavi Kelwadkar  3rd year  CSE  13 / 20   6
5   21:00:00     Abhay Vinod Sonkusare   2nd year   IT  13 / 20   7
6   21:00:21             Shreyash Hore   2nd year  CSE  13 / 20   8
7   21:06:03          Prashant Chachere  4th year  CSE  13 / 20   9
8   20:48:38               Athira Nair   3rd year  CSE   Dec-20  10
9   20:58:20         Ganesh Rahangdale   3rd year   IT   Nov-20  11
10  20:41:13         Akhilesh Titarmare  3rd year  CSE   Oct-20  12
11  20:43:26  Harsh Dnyaneshwar Lonare   3rd year  CSE   Oct-20  13
12  20:46:43              Nikhil Charde  4th year  CSE   Oct-20  14
13  20:48:23                Komal Shahu  3rd year   AI   Oct-20  15
14  20:52:28             Chhavi Padigel  2nd year   AI   Oct-20  16
15  20:56:28                Komal Koli   2nd year   AI   Oct-20  17
16  20:57:19        Diksha Manoj Kamble  3rd year   AI   Oct-20  18
17  21:03:39        Shreyas Khobragade   2nd year  CSE   Sep-20  19
18  21:05:36   Shweta Someshwar Bawane   3rd year   AI   Sep-20  20
19  20:38:32              Punam Ambule   2nd year  CSE   Aug-20  21
20  20:39:09       Pournima Y Tembhare   2nd year  CSE   Aug-20  22
21  20:41:13          Jayesh Gotephode   3rd year  CSE   Aug-20  23
22  20:52:34    Kunal Tamraj Harinkhede  3rd year  CSE   Aug-20  24
23  20:48:03           Bhumeshwar Katre  2nd year   AI   Jul-20  25
24  20:49:16           Prajwal Pakhale   2nd year  CSE   Jul-20  26
25  20:43:23               Shreya ukey   2nd year   AI   Jun-20  27
26  20:44:48              Nikhil Surkar  3rd year  CSE   Jun-20  28
27  20:46:03            Sachin Meshram   3rd year  CSE   May-20  29
28  20:49:24     ABHISHEK PRAKASH PATLE  3rd year  CSE   May-20  30
29  20:45:36    Ritik Fulchand Rajgire   3rd year  CSE   Apr-20  31
30  20:56:55         Chaitali moundekar  3rd year  CSE   Apr-20  32
31  21:00:28               Yash Dharmik  2nd year  CSE   Apr-20  33
32  20:45:22                        SAK  3rd year  CSE   Feb-20  34
33  21:03:29      Ritik Kishor Gulhane   3rd year  CSE   0 / 20  35

In [20]:
csv2 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" , nrows=4)

csv2

   20:53:27   Omkar Eknath Vaidya   3rd year  AI  16 / 20  1
0  20:51:13  Shreya Ravindra Tiple  2nd year  AI  15 / 20  2
1  21:00:53           Sahil Gedam   3rd year  IT  15 / 20  3
2  21:00:43            Akash Bitle  3rd year  IT  14 / 20  4
3  20:40:01       Dewank Bawankar   3rd year  AI  13 / 20  5

In [2]:
import pandas as pd
csv2 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" , usecols=["Name","Rank"])


csv2

                         Name  Rank
0        Omkar Eknath Vaidya      1
1       Shreya Ravindra Tiple     2
2                Sahil Gedam      3
3                 Akash Bitle     4
4            Dewank Bawankar      5
5          Bhairavi Kelwadkar     6
6      Abhay Vinod Sonkusare      7
7              Shreyash Hore      8
8           Prashant Chachere     9
9                Athira Nair     10
10         Ganesh Rahangdale     11
11         Akhilesh Titarmare    12
12  Harsh Dnyaneshwar Lonare     13
13              Nikhil Charde    14
14                Komal Shahu    15
15             Chhavi Padigel    16
16                Komal Koli     17
17        Diksha Manoj Kamble    18
18        Shreyas Khobragade     19
19   Shweta Someshwar Bawane     20
20              Punam Ambule     21
21       Pournima Y Tembhare     22
22          Jayesh Gotephode     23
23    Kunal Tamraj Harinkhede    24
24           Bhumeshwar Katre    25
25           Prajwal Pakhale     26
26               Shreya ukey     27
27              Nikhil Surkar    28
28            Sachin Meshram     29
29     ABHISHEK PRAKASH PATLE    30
30    Ritik Fulchand Rajgire     31
31         Chaitali moundekar    32
32               Yash Dharmik    33
33                        SAK    34
34      Ritik Kishor Gulhane     35

Skip row function

In [3]:
csv3 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" , skiprows=[2,3,4])
csv3

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20     1
1   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20     5
2   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20     6
3   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20     7
4   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20     8
5   21:06:03          Prashant Chachere  4th year    CSE  13 / 20     9
6   20:48:38               Athira Nair   3rd year    CSE   Dec-20    10
7   20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20    11
8   20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20    12
9   20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20    13
10  20:46:43              Nikhil Charde  4th year    CSE   Oct-20    14
11  20:48:23                Komal Shahu  3rd year     AI   Oct-20    15
12  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20    16
13  20:56:28                Komal Koli   2nd year     AI   Oct-20    17
14  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20    18
15  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20    19
16  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20    20
17  20:38:32              Punam Ambule   2nd year    CSE   Aug-20    21
18  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20    22
19  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20    23
20  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20    24
21  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20    25
22  20:49:16           Prajwal Pakhale   2nd year    CSE   Jul-20    26
23  20:43:23               Shreya ukey   2nd year     AI   Jun-20    27
24  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20    28
25  20:46:03            Sachin Meshram   3rd year    CSE   May-20    29
26  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20    30
27  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20    31
28  20:56:55         Chaitali moundekar  3rd year    CSE   Apr-20    32
29  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20    33
30  20:45:22                        SAK  3rd year    CSE   Feb-20    34
31  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20    35

indexCall

In [ ]:
csv3 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" , index_col="Name")



csv3

                               Time      Year Branch    Score  Rank
Name
Omkar Eknath Vaidya        20:53:27  3rd year     AI  16 / 20     1
Shreya Ravindra Tiple      20:51:13  2nd year     AI  15 / 20     2
Sahil Gedam                21:00:53  3rd year     IT  15 / 20     3
Akash Bitle                21:00:43  3rd year     IT  14 / 20     4
Dewank Bawankar            20:40:01  3rd year     AI  13 / 20     5
Bhairavi Kelwadkar         20:53:06  3rd year    CSE  13 / 20     6
Abhay Vinod Sonkusare      21:00:00  2nd year     IT  13 / 20     7
Shreyash Hore              21:00:21  2nd year    CSE  13 / 20     8
Prashant Chachere          21:06:03  4th year    CSE  13 / 20     9
Athira Nair                20:48:38  3rd year    CSE   Dec-20    10
Ganesh Rahangdale          20:58:20  3rd year     IT   Nov-20    11
Akhilesh Titarmare         20:41:13  3rd year    CSE   Oct-20    12
Harsh Dnyaneshwar Lonare   20:43:26  3rd year    CSE   Oct-20    13
Nikhil Charde              20:46:43  4th year    CSE   Oct-20    14
Komal Shahu                20:48:23  3rd year     AI   Oct-20    15
Chhavi Padigel             20:52:28  2nd year     AI   Oct-20    16
Komal Koli                 20:56:28  2nd year     AI   Oct-20    17
Diksha Manoj Kamble        20:57:19  3rd year     AI   Oct-20    18
Shreyas Khobragade         21:03:39  2nd year    CSE   Sep-20    19
Shweta Someshwar Bawane    21:05:36  3rd year     AI   Sep-20    20
Punam Ambule               20:38:32  2nd year    CSE   Aug-20    21
Pournima Y Tembhare        20:39:09  2nd year    CSE   Aug-20    22
Jayesh Gotephode           20:41:13  3rd year    CSE   Aug-20    23
Kunal Tamraj Harinkhede    20:52:34  3rd year    CSE   Aug-20    24
Bhumeshwar Katre           20:48:03  2nd year     AI   Jul-20    25
Prajwal Pakhale            20:49:16  2nd year    CSE   Jul-20    26
Shreya ukey                20:43:23  2nd year     AI   Jun-20    27
Nikhil Surkar              20:44:48  3rd year    CSE   Jun-20    28
Sachin Meshram             20:46:03  3rd year    CSE   May-20    29
ABHISHEK PRAKASH PATLE     20:49:24  3rd year    CSE   May-20    30
Ritik Fulchand Rajgire     20:45:36  3rd year    CSE   Apr-20    31
Chaitali moundekar         20:56:55  3rd year    CSE   Apr-20    32
Yash Dharmik               21:00:28  2nd year    CSE   Apr-20    33
SAK                        20:45:22  3rd year    CSE   Feb-20    34
Ritik Kishor Gulhane       21:03:29  3rd year    CSE   0 / 20    35

In [4]:
csv4 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" ,header=2)



csv4

    20:51:13      Shreya Ravindra Tiple  2nd year   AI  15 / 20   2
0   21:00:53               Sahil Gedam   3rd year   IT  15 / 20   3
1   21:00:43                Akash Bitle  3rd year   IT  14 / 20   4
2   20:40:01           Dewank Bawankar   3rd year   AI  13 / 20   5
3   20:53:06         Bhairavi Kelwadkar  3rd year  CSE  13 / 20   6
4   21:00:00     Abhay Vinod Sonkusare   2nd year   IT  13 / 20   7
5   21:00:21             Shreyash Hore   2nd year  CSE  13 / 20   8
6   21:06:03          Prashant Chachere  4th year  CSE  13 / 20   9
7   20:48:38               Athira Nair   3rd year  CSE   Dec-20  10
8   20:58:20         Ganesh Rahangdale   3rd year   IT   Nov-20  11
9   20:41:13         Akhilesh Titarmare  3rd year  CSE   Oct-20  12
10  20:43:26  Harsh Dnyaneshwar Lonare   3rd year  CSE   Oct-20  13
11  20:46:43              Nikhil Charde  4th year  CSE   Oct-20  14
12  20:48:23                Komal Shahu  3rd year   AI   Oct-20  15
13  20:52:28             Chhavi Padigel  2nd year   AI   Oct-20  16
14  20:56:28                Komal Koli   2nd year   AI   Oct-20  17
15  20:57:19        Diksha Manoj Kamble  3rd year   AI   Oct-20  18
16  21:03:39        Shreyas Khobragade   2nd year  CSE   Sep-20  19
17  21:05:36   Shweta Someshwar Bawane   3rd year   AI   Sep-20  20
18  20:38:32              Punam Ambule   2nd year  CSE   Aug-20  21
19  20:39:09       Pournima Y Tembhare   2nd year  CSE   Aug-20  22
20  20:41:13          Jayesh Gotephode   3rd year  CSE   Aug-20  23
21  20:52:34    Kunal Tamraj Harinkhede  3rd year  CSE   Aug-20  24
22  20:48:03           Bhumeshwar Katre  2nd year   AI   Jul-20  25
23  20:49:16           Prajwal Pakhale   2nd year  CSE   Jul-20  26
24  20:43:23               Shreya ukey   2nd year   AI   Jun-20  27
25  20:44:48              Nikhil Surkar  3rd year  CSE   Jun-20  28
26  20:46:03            Sachin Meshram   3rd year  CSE   May-20  29
27  20:49:24     ABHISHEK PRAKASH PATLE  3rd year  CSE   May-20  30
28  20:45:36    Ritik Fulchand Rajgire   3rd year  CSE   Apr-20  31
29  20:56:55         Chaitali moundekar  3rd year  CSE   Apr-20  32
30  21:00:28               Yash Dharmik  2nd year  CSE   Apr-20  33
31  20:45:22                        SAK  3rd year  CSE   Feb-20  34
32  21:03:29      Ritik Kishor Gulhane   3rd year  CSE   0 / 20  35

In [ ]:
csv3 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" , names=['TIme' , "namr","year","branch" ,"score","rank"])



csv3

        TIme                       namr      year  branch    score  rank
0       Time                       Name      Year  Branch    Score  Rank
1   20:53:27       Omkar Eknath Vaidya   3rd year      AI  16 / 20     1
2   20:51:13      Shreya Ravindra Tiple  2nd year      AI  15 / 20     2
3   21:00:53               Sahil Gedam   3rd year      IT  15 / 20     3
4   21:00:43                Akash Bitle  3rd year      IT  14 / 20     4
5   20:40:01           Dewank Bawankar   3rd year      AI  13 / 20     5
6   20:53:06         Bhairavi Kelwadkar  3rd year     CSE  13 / 20     6
7   21:00:00     Abhay Vinod Sonkusare   2nd year      IT  13 / 20     7
8   21:00:21             Shreyash Hore   2nd year     CSE  13 / 20     8
9   21:06:03          Prashant Chachere  4th year     CSE  13 / 20     9
10  20:48:38               Athira Nair   3rd year     CSE   Dec-20    10
11  20:58:20         Ganesh Rahangdale   3rd year      IT   Nov-20    11
12  20:41:13         Akhilesh Titarmare  3rd year     CSE   Oct-20    12
13  20:43:26  Harsh Dnyaneshwar Lonare   3rd year     CSE   Oct-20    13
14  20:46:43              Nikhil Charde  4th year     CSE   Oct-20    14
15  20:48:23                Komal Shahu  3rd year      AI   Oct-20    15
16  20:52:28             Chhavi Padigel  2nd year      AI   Oct-20    16
17  20:56:28                Komal Koli   2nd year      AI   Oct-20    17
18  20:57:19        Diksha Manoj Kamble  3rd year      AI   Oct-20    18
19  21:03:39        Shreyas Khobragade   2nd year     CSE   Sep-20    19
20  21:05:36   Shweta Someshwar Bawane   3rd year      AI   Sep-20    20
21  20:38:32              Punam Ambule   2nd year     CSE   Aug-20    21
22  20:39:09       Pournima Y Tembhare   2nd year     CSE   Aug-20    22
23  20:41:13          Jayesh Gotephode   3rd year     CSE   Aug-20    23
24  20:52:34    Kunal Tamraj Harinkhede  3rd year     CSE   Aug-20    24
25  20:48:03           Bhumeshwar Katre  2nd year      AI   Jul-20    25
26  20:49:16           Prajwal Pakhale   2nd year     CSE   Jul-20    26
27  20:43:23               Shreya ukey   2nd year      AI   Jun-20    27
28  20:44:48              Nikhil Surkar  3rd year     CSE   Jun-20    28
29  20:46:03            Sachin Meshram   3rd year     CSE   May-20    29
30  20:49:24     ABHISHEK PRAKASH PATLE  3rd year     CSE   May-20    30
31  20:45:36    Ritik Fulchand Rajgire   3rd year     CSE   Apr-20    31
32  20:56:55         Chaitali moundekar  3rd year     CSE   Apr-20    32
33  21:00:28               Yash Dharmik  2nd year     CSE   Apr-20    33
34  20:45:22                        SAK  3rd year     CSE   Feb-20    34
35  21:03:29      Ritik Kishor Gulhane   3rd year     CSE   0 / 20    35

In [32]:
csv3 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv" ,header=None  ,prefix="col")



csv3

        col0                       col1      col2 col3     col4  col5
0   20:53:27       Omkar Eknath Vaidya   3rd year   AI  16 / 20     1
1   20:51:13      Shreya Ravindra Tiple  2nd year   AI  15 / 20     2
2   21:00:53               Sahil Gedam   3rd year   IT  15 / 20     3
3   21:00:43                Akash Bitle  3rd year   IT  14 / 20     4
4   20:40:01           Dewank Bawankar   3rd year   AI  13 / 20     5
5   20:53:06         Bhairavi Kelwadkar  3rd year  CSE  13 / 20     6
6   21:00:00     Abhay Vinod Sonkusare   2nd year   IT  13 / 20     7
7   21:00:21             Shreyash Hore   2nd year  CSE  13 / 20     8
8   21:06:03          Prashant Chachere  4th year  CSE  13 / 20     9
9   20:48:38               Athira Nair   3rd year  CSE   Dec-20    10
10  20:58:20         Ganesh Rahangdale   3rd year   IT   Nov-20    11
11  20:41:13         Akhilesh Titarmare  3rd year  CSE   Oct-20    12
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year  CSE   Oct-20    13
13  20:46:43              Nikhil Charde  4th year  CSE   Oct-20    14
14  20:48:23                Komal Shahu  3rd year   AI   Oct-20    15
15  20:52:28             Chhavi Padigel  2nd year   AI   Oct-20    16
16  20:56:28                Komal Koli   2nd year   AI   Oct-20    17
17  20:57:19        Diksha Manoj Kamble  3rd year   AI   Oct-20    18
18  21:03:39        Shreyas Khobragade   2nd year  CSE   Sep-20    19
19  21:05:36   Shweta Someshwar Bawane   3rd year   AI   Sep-20    20
20  20:38:32              Punam Ambule   2nd year  CSE   Aug-20    21
21  20:39:09       Pournima Y Tembhare   2nd year  CSE   Aug-20    22
22  20:41:13          Jayesh Gotephode   3rd year  CSE   Aug-20    23
23  20:52:34    Kunal Tamraj Harinkhede  3rd year  CSE   Aug-20    24
24  20:48:03           Bhumeshwar Katre  2nd year   AI   Jul-20    25
25  20:49:16           Prajwal Pakhale   2nd year  CSE   Jul-20    26
26  20:43:23               Shreya ukey   2nd year   AI   Jun-20    27
27  20:44:48              Nikhil Surkar  3rd year  CSE   Jun-20    28
28  20:46:03            Sachin Meshram   3rd year  CSE   May-20    29
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year  CSE   May-20    30
30  20:45:36    Ritik Fulchand Rajgire   3rd year  CSE   Apr-20    31
31  20:56:55         Chaitali moundekar  3rd year  CSE   Apr-20    32
32  21:00:28               Yash Dharmik  2nd year  CSE   Apr-20    33
33  20:45:22                        SAK  3rd year  CSE   Feb-20    34
34  21:03:29      Ritik Kishor Gulhane   3rd year  CSE   0 / 20    35

Data Type Change in pandas

In [39]:
csv3 = pd.read_csv("E:\\learing code\\Data Science\\pandas\\record.csv",dtype={"Rank":"float"} )



csv3

        Time                       Name      Year Branch    Score  Rank
0   20:53:27       Omkar Eknath Vaidya   3rd year     AI  16 / 20   1.0
1   20:51:13      Shreya Ravindra Tiple  2nd year     AI  15 / 20   2.0
2   21:00:53               Sahil Gedam   3rd year     IT  15 / 20   3.0
3   21:00:43                Akash Bitle  3rd year     IT  14 / 20   4.0
4   20:40:01           Dewank Bawankar   3rd year     AI  13 / 20   5.0
5   20:53:06         Bhairavi Kelwadkar  3rd year    CSE  13 / 20   6.0
6   21:00:00     Abhay Vinod Sonkusare   2nd year     IT  13 / 20   7.0
7   21:00:21             Shreyash Hore   2nd year    CSE  13 / 20   8.0
8   21:06:03          Prashant Chachere  4th year    CSE  13 / 20   9.0
9   20:48:38               Athira Nair   3rd year    CSE   Dec-20  10.0
10  20:58:20         Ganesh Rahangdale   3rd year     IT   Nov-20  11.0
11  20:41:13         Akhilesh Titarmare  3rd year    CSE   Oct-20  12.0
12  20:43:26  Harsh Dnyaneshwar Lonare   3rd year    CSE   Oct-20  13.0
13  20:46:43              Nikhil Charde  4th year    CSE   Oct-20  14.0
14  20:48:23                Komal Shahu  3rd year     AI   Oct-20  15.0
15  20:52:28             Chhavi Padigel  2nd year     AI   Oct-20  16.0
16  20:56:28                Komal Koli   2nd year     AI   Oct-20  17.0
17  20:57:19        Diksha Manoj Kamble  3rd year     AI   Oct-20  18.0
18  21:03:39        Shreyas Khobragade   2nd year    CSE   Sep-20  19.0
19  21:05:36   Shweta Someshwar Bawane   3rd year     AI   Sep-20  20.0
20  20:38:32              Punam Ambule   2nd year    CSE   Aug-20  21.0
21  20:39:09       Pournima Y Tembhare   2nd year    CSE   Aug-20  22.0
22  20:41:13          Jayesh Gotephode   3rd year    CSE   Aug-20  23.0
23  20:52:34    Kunal Tamraj Harinkhede  3rd year    CSE   Aug-20  24.0
24  20:48:03           Bhumeshwar Katre  2nd year     AI   Jul-20  25.0
25  20:49:16           Prajwal Pakhale   2nd year    CSE   Jul-20  26.0
26  20:43:23               Shreya ukey   2nd year     AI   Jun-20  27.0
27  20:44:48              Nikhil Surkar  3rd year    CSE   Jun-20  28.0
28  20:46:03            Sachin Meshram   3rd year    CSE   May-20  29.0
29  20:49:24     ABHISHEK PRAKASH PATLE  3rd year    CSE   May-20  30.0
30  20:45:36    Ritik Fulchand Rajgire   3rd year    CSE   Apr-20  31.0
31  20:56:55         Chaitali moundekar  3rd year    CSE   Apr-20  32.0
32  21:00:28               Yash Dharmik  2nd year    CSE   Apr-20  33.0
33  20:45:22                        SAK  3rd year    CSE   Feb-20  34.0
34  21:03:29      Ritik Kishor Gulhane   3rd year    CSE   0 / 20  35.0